version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type: task"
      - "status: waiting-for-triage"
  - package-ecosystem: "npm"
    directory: "/antora"
    schedule:
      interval: "weekly"
    labels:
      - "type: task"
      - "status: waiting-for-triage"
